apiVersion: v1 
kind: pod
metadata:
        name: app-pod
        labels:
                name: app-pod
                app: HappyTrip-App 
spec:
        containers:
                - name: app
                  image: vmady/happy_trip:happytripapp
                  ports:
                          - containerPort: 90
