apiVersion: v1
kind: Deployment
metadata:
        name: app-deployment
        labels:
                app: HappyTrip-App
spec:
        replicas: 1
        selector:
                matchLables:
                        name: app-pod
                        app: HappyTrip-App
                template:
                        metadata:
                                name: app-pod
                                lables:
                                        name: app-pod
                                        app: HappyTrip-App
                        spec:
                                containers:
                                        - name: app
                                          image: vmady/happy_trip:happytripapp 
                                          ports:
                                                  - containerPort: 90
