apiVersion: v1
kind: Service
metadata:
        name: app-service
        lables:
                name: app-service
                app: HappyTrip-App
spec:
        type: LoadBalancer
        ports:
                - port: 90
                  targetPort: 90
        selector:
                name: app-pod
                app: HappyTrip-App
