apiVersion: v1
kind: Service
metadata:
        name: db-service
        labels:
                name: db-service
                app: HappyTrip-App
spec:
        ports:
                - port: 3306
                  targetPort: 3306
        selector:
                name: mysql-pod
                app: HappyTrip-App
                
