apiVersion: apps/v1
kind: Deployment
metadata:
        name: mysql-deployment
        labels:
                app: HappyTrip-App
spec:
        replicas: 1
        selector:
                matchLabels:
                        name: mysql-pod
                        app: HappyTrip-App
        template:
                 metadata:
                         name: mysql-pod
                         labels:
                                name: mysql-pod
                                app: HappyTrip-App
                 spec:
                     containers:
                      - name: mysql
                        image: vmady/happy_trip:happytripdb
                        ports:
                         - containerPort: 3306


